# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c3f5da86ce467e50e9d98872b575b2f8dc4125c92bd5631dd3bdc24e02be8874bce0f5db933d5251729775e013014d60b764cb8a05914c2c03f9ecac7518297

test:
  secret_key_base: 54ee3bdf11161eb78ab8b9e6a1d2dd71cc665e20dc47f1c959954b661b0d7b82d04cf0174c2ef2f4676ebac92cab6a70ea43c71940727bec5585559b5566e77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
